apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: barber-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: backend
          image: 192.168.100.20:5000/barber-shop/backend:latest
          imagePullPolicy: Always    # <-- set your real tag
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.barber-shop.svc.cluster.local:3306/barber_shop_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"   # fine for a lab; use "validate" + migrations (Flyway/Liquibase) later
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 1
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: barber-shop
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
